base_url = "https://quirky-perlman-34d0da.netlify.com"
title = "Light Speed"
description = "Zola theme with a perfect Lighthouse score"

compile_sass = true
generate_feed = true

highlight_code = true
highlight_theme = "gruvbox-light"

[extra]

seo = true
author = "El Carpet"
ogimage = "lightning.png"